const fs = require('fs');

const dataPath = 'c:/Users/rampr/OneDrive/Desktop/Rentel/src/features/listings/listingsData.js';
let dataContent = fs.readFileSync(dataPath, 'utf8');

// The original file is a module exporting an array.
// Let's use eval or string manipulation.
// Actually, it's simpler to just overwrite the entire file with all 60 listings statically defined.

const newContent = `export const listingsData = [
  // ================= HOLIDAY STAYS =================
  // JAIPUR (5)
  { id: 1, title: "The Royal Heritage Villa", type: "villa", rentMode: "holiday", city: "Jaipur", location: "Amer Road, Jaipur", state: "Rajasthan", price: 6250, rating: 4.9, reviews: 128, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"], featured: true, categoryTags: ["Luxury", "Heritage"] },
  { id: 13, title: "Pink City Studio", type: "flat", rentMode: "holiday", city: "Jaipur", location: "C-Scheme, Jaipur", state: "Rajasthan", price: 2500, rating: 4.8, reviews: 45, badge: "Superhost", images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], featured: false, categoryTags: ["Work-Friendly"] },
  { id: 14, title: "Jaipur Desert Camp", type: "farmhouse", rentMode: "holiday", city: "Jaipur", location: "Nahargarh, Jaipur", state: "Rajasthan", price: 4500, rating: 4.7, reviews: 32, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800"], featured: false, categoryTags: ["Farmhouse"] },
  { id: 23, title: "Nahargarh View Suite", type: "hotel", rentMode: "holiday", city: "Jaipur", location: "Hawa Mahal Rd, Jaipur", state: "Rajasthan", price: 3800, rating: 4.6, reviews: 78, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800"], featured: false, categoryTags: ["Luxury"] },
  { id: 24, title: "Rajasthani Haveli Stay", type: "villa", rentMode: "holiday", city: "Jaipur", location: "Civil Lines, Jaipur", state: "Rajasthan", price: 5500, rating: 4.9, reviews: 56, badge: "Superhost", images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"], featured: true, categoryTags: ["Heritage"] },

  // GOA (5)
  { id: 2, title: "Seaside Bliss Apartment", type: "flat", rentMode: "holiday", city: "Goa", location: "Candolim, Goa", state: "Goa", price: 4500, rating: 4.8, reviews: 85, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"], featured: true, categoryTags: ["Beach Villa", "Work-Friendly"] },
  { id: 15, title: "Goa Palms Villa", type: "villa", rentMode: "holiday", city: "Goa", location: "Vagator, Goa", state: "Goa", price: 8500, rating: 4.9, reviews: 67, badge: "Superhost", images: ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800"], featured: true, categoryTags: ["Beach Villa", "With Pool"] },
  { id: 16, title: "Anjuna Beach House", type: "flat", rentMode: "holiday", city: "Goa", location: "Anjuna, Goa", state: "Goa", price: 3200, rating: 4.6, reviews: 92, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"], featured: false, categoryTags: ["Beach Villa"] },
  { id: 25, title: "Baga Beachfront Resort", type: "hotel", rentMode: "holiday", city: "Goa", location: "Baga, Goa", state: "Goa", price: 5800, rating: 4.5, reviews: 145, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1534850336045-c6c6d287f89e?w=800"], featured: false, categoryTags: ["Beach Villa"] },
  { id: 26, title: "Luxury Mandovi Villa", type: "villa", rentMode: "holiday", city: "Goa", location: "Panjim, Goa", state: "Goa", price: 12500, rating: 5.0, reviews: 34, badge: "Superhost", images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800"], featured: true, categoryTags: ["With Pool"] },

  // MUMBAI (5)
  { id: 17, title: "Marine Drive View Flat", type: "flat", rentMode: "holiday", city: "Mumbai", location: "Marine Drive, Mumbai", state: "Maharashtra", price: 12000, rating: 5.0, reviews: 15, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], featured: true, categoryTags: ["Luxury"] },
  { id: 18, title: "Bandra Boutique Stay", type: "hotel", rentMode: "holiday", city: "Mumbai", location: "Bandra, Mumbai", state: "Maharashtra", price: 5500, rating: 4.7, reviews: 58, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"], featured: false, categoryTags: [] },
  { id: 27, title: "Juhu Beach Loft", type: "flat", rentMode: "holiday", city: "Mumbai", location: "Juhu, Mumbai", state: "Maharashtra", price: 8500, rating: 4.8, reviews: 21, badge: "Superhost", images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800"], featured: false, categoryTags: ["Luxury"] },

  // BANGALORE (5)
  { id: 19, title: "Tech Park Apartment", type: "flat", rentMode: "holiday", city: "Bangalore", location: "Whitefield, Bangalore", state: "Karnataka", price: 3500, rating: 4.5, reviews: 24, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800"], featured: false, categoryTags: ["Work-Friendly"] },
  { id: 20, title: "Indiranagar Green House", type: "villa", rentMode: "holiday", city: "Bangalore", location: "Indiranagar, Bangalore", state: "Karnataka", price: 7500, rating: 4.8, reviews: 12, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"], featured: true, categoryTags: ["Family Stay"] },
  { id: 29, title: "HSR Layout Studio", type: "flat", rentMode: "holiday", city: "Bangalore", location: "HSR Layout, Bangalore", state: "Karnataka", price: 2800, rating: 4.6, reviews: 18, badge: "Superhost", images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], featured: false, categoryTags: ["Work-Friendly"] },

  // MANALI (5)
  { id: 4, title: "The Himalayan Retreat", type: "farmhouse", rentMode: "holiday", city: "Manali", location: "Old Manali, Himachal", state: "Himachal Pradesh", price: 4250, rating: 4.9, reviews: 64, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"], featured: true, categoryTags: ["Hill Station", "Pet Friendly"] },
  { id: 21, title: "Snowy Peak Villa", type: "villa", rentMode: "holiday", city: "Manali", location: "Solang Valley, Manali", state: "Himachal Pradesh", price: 9500, rating: 4.9, reviews: 41, badge: "Superhost", images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"], featured: true, categoryTags: ["Hill Station", "With Pool"] },
  { id: 22, title: "Mountain Mist Cottage", type: "farmhouse", rentMode: "holiday", city: "Manali", location: "Mall Road, Manali", state: "Himachal Pradesh", price: 3800, rating: 4.7, reviews: 29, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"], featured: false, categoryTags: ["Hill Station"] },
  { id: 31, title: "Rohtang Pass View", type: "hotel", rentMode: "holiday", city: "Manali", location: "Near Rohtang, Manali", state: "Himachal Pradesh", price: 6500, rating: 4.8, reviews: 82, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1518733057094-95b53143d2a7?w=800"], featured: true, categoryTags: ["Hill Station"] },
  { id: 32, title: "River Side Log Cabin", type: "farmhouse", rentMode: "holiday", city: "Manali", location: "Beas River, Manali", state: "Himachal Pradesh", price: 5200, rating: 4.9, reviews: 14, badge: "Superhost", images: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"], featured: false, categoryTags: ["Hill Station"] },

  // ================= RENT STAYS =================
  { id: 101, title: "Spacious 3 BHK in Koramangala", type: "flat", propertyType: "3 BHK", rentMode: "rent", city: "Bangalore", location: "Koramangala, Bangalore", state: "Karnataka", price: 45000, rating: 4.8, reviews: 12, badge: "Superhost", images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], featured: true, categoryTags: ["Family Stay"] },
  { id: 102, title: "Premium 2 BHK Near Metro", type: "flat", propertyType: "2 BHK", rentMode: "rent", city: "Bangalore", location: "Indiranagar, Bangalore", state: "Karnataka", price: 32000, rating: 4.5, reviews: 24, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"], featured: false, categoryTags: [] },
  { id: 103, title: "Luxury Sea View Flat", type: "flat", propertyType: "Flat", rentMode: "rent", city: "Mumbai", location: "Worli, Mumbai", state: "Maharashtra", price: 85000, rating: 4.9, reviews: 31, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800"], featured: true, categoryTags: ["Luxury"] },
  { id: 104, title: "Compact 1 BHK Andheri", type: "flat", propertyType: "1 BHK", rentMode: "rent", city: "Mumbai", location: "Andheri West, Mumbai", state: "Maharashtra", price: 28000, rating: 4.4, reviews: 8, badge: "", images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800"], featured: false, categoryTags: [] },
  { id: 105, title: "Independent Villa in Assagao", type: "villa", propertyType: "House/Villa", rentMode: "rent", city: "Goa", location: "Assagao, Goa", state: "Goa", price: 65000, rating: 4.7, reviews: 14, badge: "Superhost", images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800"], featured: false, categoryTags: ["With Pool"] },
  { id: 106, title: "Commercial Office Space", type: "commercial", propertyType: "Office", rentMode: "rent", city: "Bangalore", location: "Whitefield, Bangalore", state: "Karnataka", price: 120000, rating: 4.2, reviews: 3, badge: "", images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"], featured: false, categoryTags: [] },
  { id: 107, title: "Retail Shop on Main Road", type: "commercial", propertyType: "Shop", rentMode: "rent", city: "Jaipur", location: "Malviya Nagar, Jaipur", state: "Rajasthan", price: 40000, rating: 4.6, reviews: 5, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1582055610731-893fa141eab1?w=800"], featured: false, categoryTags: [] },
  { id: 108, title: "Modern 4+ BHK Duplex", type: "flat", propertyType: "4+ BHK", rentMode: "rent", city: "Mumbai", location: "Bandra West, Mumbai", state: "Maharashtra", price: 150000, rating: 5.0, reviews: 11, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], featured: true, categoryTags: ["Luxury"] },
  { id: 109, title: "Agricultural Land For Lease", type: "land", propertyType: "Agricultural Land", rentMode: "rent", city: "Jaipur", location: "Sanganer, Jaipur", state: "Rajasthan", price: 15000, rating: 4.1, reviews: 2, badge: "", images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"], featured: false, categoryTags: [] },
  { id: 110, title: "Cozy 1 BHK in Candolim", type: "flat", propertyType: "1 BHK", rentMode: "rent", city: "Goa", location: "Candolim, Goa", state: "Goa", price: 22000, rating: 4.5, reviews: 29, badge: "", images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"], featured: false, categoryTags: [] },

  // ================= PG STAYS =================
  { id: 201, title: "Sunrise Boys PG", type: "pg", rentMode: "pg", pgGender: "Boys", pgType: "Double Sharing", city: "Bangalore", location: "BTM Layout, Bangalore", state: "Karnataka", price: 8500, rating: 4.3, reviews: 56, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"], featured: false, categoryTags: [] },
  { id: 202, title: "Elite Girls Co-living", type: "pg", rentMode: "pg", pgGender: "Girls", pgType: "Single Room", city: "Bangalore", location: "HSR Layout, Bangalore", state: "Karnataka", price: 14000, rating: 4.8, reviews: 34, badge: "Superhost", images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800"], featured: true, categoryTags: [] },
  { id: 203, title: "Urban Nest Co-ed PG", type: "pg", rentMode: "pg", pgGender: "Co-ed", pgType: "Shared-Flat", city: "Mumbai", location: "Powai, Mumbai", state: "Maharashtra", price: 16000, rating: 4.7, reviews: 41, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], featured: false, categoryTags: [] },
  { id: 204, title: "Budget Boys PG", type: "pg", rentMode: "pg", pgGender: "Boys", pgType: "Triple Sharing", city: "Jaipur", location: "Tonk Road, Jaipur", state: "Rajasthan", price: 4500, rating: 4.0, reviews: 18, badge: "", images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"], featured: false, categoryTags: [] },
  { id: 205, title: "Premium Girls PG", type: "pg", rentMode: "pg", pgGender: "Girls", pgType: "Double Sharing", city: "Jaipur", location: "Malviya Nagar, Jaipur", state: "Rajasthan", price: 7500, rating: 4.5, reviews: 22, badge: "Superhost", images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800"], featured: false, categoryTags: [] },
  { id: 206, title: "Sea Breeze Boys PG", type: "pg", rentMode: "pg", pgGender: "Boys", pgType: "Shared-Flat", city: "Goa", location: "Panjim, Goa", state: "Goa", price: 9000, rating: 4.2, reviews: 15, badge: "", images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], featured: false, categoryTags: [] },
  { id: 207, title: "Luxury Girls Accommodation", type: "pg", rentMode: "pg", pgGender: "Girls", pgType: "Single Room", city: "Mumbai", location: "South Mumbai", state: "Maharashtra", price: 25000, rating: 4.9, reviews: 11, badge: "Top Rated", images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800"], featured: true, categoryTags: [] },
  { id: 208, title: "Techies Co-ed Coliving", type: "pg", rentMode: "pg", pgGender: "Co-ed", pgType: "Room/Bed in a Shared-Flat", city: "Bangalore", location: "Electronic City, Bangalore", state: "Karnataka", price: 11000, rating: 4.4, reviews: 89, badge: "Guest favourite", images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"], featured: false, categoryTags: [] },
  { id: 209, title: "Himalayan Co-ed Stay", type: "pg", rentMode: "pg", pgGender: "Co-ed", pgType: "Double Sharing", city: "Manali", location: "Old Manali", state: "Himachal Pradesh", price: 6000, rating: 4.6, reviews: 27, badge: "", images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"], featured: false, categoryTags: [] },
  { id: 210, title: "Student Boys Hostel", type: "pg", rentMode: "pg", pgGender: "Boys", pgType: "Triple Sharing", city: "Bangalore", location: "Mathikere, Bangalore", state: "Karnataka", price: 5500, rating: 3.9, reviews: 112, badge: "", images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"], featured: false, categoryTags: [] }
];
`;

fs.writeFileSync(dataPath, newContent);
console.log('Listings generated successfully.');
