export const listingsData = [
  // JAIPUR (5)
  {
    id: 1,
    title: "The Royal Heritage Villa",
    type: "villa",
    city: "Jaipur",
    location: "Amer Road, Jaipur",
    state: "Rajasthan",
    price: 6250,
    rating: 4.9,
    reviews: 128,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"],
    featured: true,
    categoryTags: ["Luxury", "Heritage"]
  },
  {
    id: 13,
    title: "Pink City Studio",
    type: "flat",
    city: "Jaipur",
    location: "C-Scheme, Jaipur",
    state: "Rajasthan",
    price: 2500,
    rating: 4.8,
    reviews: 45,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    featured: false,
    categoryTags: ["City PG", "Work-Friendly"]
  },
  {
    id: 14,
    title: "Jaipur Desert Camp",
    type: "farmhouse",
    city: "Jaipur",
    location: "Nahargarh, Jaipur",
    state: "Rajasthan",
    price: 4500,
    rating: 4.7,
    reviews: 32,
    badge: "Top Rated",
    images: ["https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800"],
    featured: false,
    categoryTags: ["Farmhouse"]
  },
  {
    id: 23,
    title: "Nahargarh View Suite",
    type: "hotel",
    city: "Jaipur",
    location: "Hawa Mahal Rd, Jaipur",
    state: "Rajasthan",
    price: 3800,
    rating: 4.6,
    reviews: 78,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800"],
    featured: false,
    categoryTags: ["Luxury"]
  },
  {
    id: 24,
    title: "Rajasthani Haveli Stay",
    type: "villa",
    city: "Jaipur",
    location: "Civil Lines, Jaipur",
    state: "Rajasthan",
    price: 5500,
    rating: 4.9,
    reviews: 56,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    featured: true,
    categoryTags: ["Heritage"]
  },

  // GOA (5)
  {
    id: 2,
    title: "Seaside Bliss Apartment",
    type: "flat",
    city: "Goa",
    location: "Candolim, Goa",
    state: "Goa",
    price: 4500,
    rating: 4.8,
    reviews: 85,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
    featured: true,
    categoryTags: ["Beach Villa", "Work-Friendly"]
  },
  {
    id: 15,
    title: "Goa Palms Villa",
    type: "villa",
    city: "Goa",
    location: "Vagator, Goa",
    state: "Goa",
    price: 8500,
    rating: 4.9,
    reviews: 67,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800"],
    featured: true,
    categoryTags: ["Beach Villa", "With Pool"]
  },
  {
    id: 16,
    title: "Anjuna Beach House",
    type: "flat",
    city: "Goa",
    location: "Anjuna, Goa",
    state: "Goa",
    price: 3200,
    rating: 4.6,
    reviews: 92,
    badge: "Top Rated",
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    featured: false,
    categoryTags: ["Beach Villa"]
  },
  {
    id: 25,
    title: "Baga Beachfront Resort",
    type: "hotel",
    city: "Goa",
    location: "Baga, Goa",
    state: "Goa",
    price: 5800,
    rating: 4.5,
    reviews: 145,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1534850336045-c6c6d287f89e?w=800"],
    featured: false,
    categoryTags: ["Beach Villa"]
  },
  {
    id: 26,
    title: "Luxury Mandovi Villa",
    type: "villa",
    city: "Goa",
    location: "Panjim, Goa",
    state: "Goa",
    price: 12500,
    rating: 5.0,
    reviews: 34,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800"],
    featured: true,
    categoryTags: ["With Pool"]
  },

  // MUMBAI (5)
  {
    id: 3,
    title: "Urban Nest Luxury PG",
    type: "pg",
    city: "Mumbai",
    location: "Andheri West, Mumbai",
    state: "Maharashtra",
    price: 1800,
    rating: 4.6,
    reviews: 42,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800"],
    featured: false,
    categoryTags: ["City PG", "Work-Friendly"]
  },
  {
    id: 17,
    title: "Marine Drive View Flat",
    type: "flat",
    city: "Mumbai",
    location: "Marine Drive, Mumbai",
    state: "Maharashtra",
    price: 12000,
    rating: 5.0,
    reviews: 15,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    featured: true,
    categoryTags: ["Luxury"]
  },
  {
    id: 18,
    title: "Bandra Boutique Stay",
    type: "hotel",
    city: "Mumbai",
    location: "Bandra, Mumbai",
    state: "Maharashtra",
    price: 5500,
    rating: 4.7,
    reviews: 58,
    badge: "Top Rated",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    featured: false,
    categoryTags: ["City PG"]
  },
  {
    id: 27,
    title: "Juhu Beach Loft",
    type: "flat",
    city: "Mumbai",
    location: "Juhu, Mumbai",
    state: "Maharashtra",
    price: 8500,
    rating: 4.8,
    reviews: 21,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800"],
    featured: false,
    categoryTags: ["Luxury"]
  },
  {
    id: 28,
    title: "Colaba Heritage PG",
    type: "pg",
    city: "Mumbai",
    location: "Colaba, Mumbai",
    state: "Maharashtra",
    price: 2200,
    rating: 4.4,
    reviews: 65,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    featured: false,
    categoryTags: ["City PG"]
  },

  // BANGALORE (5)
  {
    id: 10,
    title: "Sunrise Heights PG",
    type: "pg",
    city: "Bangalore",
    location: "Koramangala, Bangalore",
    state: "Karnataka",
    price: 1500,
    rating: 4.4,
    reviews: 31,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800"],
    featured: false,
    categoryTags: ["City PG", "Work-Friendly"]
  },
  {
    id: 19,
    title: "Tech Park Apartment",
    type: "flat",
    city: "Bangalore",
    location: "Whitefield, Bangalore",
    state: "Karnataka",
    price: 3500,
    rating: 4.5,
    reviews: 24,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800"],
    featured: false,
    categoryTags: ["Work-Friendly"]
  },
  {
    id: 20,
    title: "Indiranagar Green House",
    type: "villa",
    city: "Bangalore",
    location: "Indiranagar, Bangalore",
    state: "Karnataka",
    price: 7500,
    rating: 4.8,
    reviews: 12,
    badge: "Top Rated",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
    featured: true,
    categoryTags: ["Family Stay"]
  },
  {
    id: 29,
    title: "HSR Layout Studio",
    type: "flat",
    city: "Bangalore",
    location: "HSR Layout, Bangalore",
    state: "Karnataka",
    price: 2800,
    rating: 4.6,
    reviews: 18,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    featured: false,
    categoryTags: ["Work-Friendly"]
  },
  {
    id: 30,
    title: "Electronic City Stay",
    type: "pg",
    city: "Bangalore",
    location: "Electronic City, Bangalore",
    state: "Karnataka",
    price: 1200,
    rating: 4.3,
    reviews: 47,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800"],
    featured: false,
    categoryTags: ["City PG"]
  },

  // MANALI (5)
  {
    id: 4,
    title: "The Himalayan Retreat",
    type: "farmhouse",
    city: "Manali",
    location: "Old Manali, Himachal",
    state: "Himachal Pradesh",
    price: 4250,
    rating: 4.9,
    reviews: 64,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"],
    featured: true,
    categoryTags: ["Hill Station", "Pet Friendly"]
  },
  {
    id: 21,
    title: "Snowy Peak Villa",
    type: "villa",
    city: "Manali",
    location: "Solang Valley, Manali",
    state: "Himachal Pradesh",
    price: 9500,
    rating: 4.9,
    reviews: 41,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    featured: true,
    categoryTags: ["Hill Station", "With Pool"]
  },
  {
    id: 22,
    title: "Mountain Mist Cottage",
    type: "farmhouse",
    city: "Manali",
    location: "Mall Road, Manali",
    state: "Himachal Pradesh",
    price: 3800,
    rating: 4.7,
    reviews: 29,
    badge: "Top Rated",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"],
    featured: false,
    categoryTags: ["Hill Station"]
  },
  {
    id: 31,
    title: "Rohtang Pass View",
    type: "hotel",
    city: "Manali",
    location: "Near Rohtang, Manali",
    state: "Himachal Pradesh",
    price: 6500,
    rating: 4.8,
    reviews: 82,
    badge: "Guest favourite",
    images: ["https://images.unsplash.com/photo-1518733057094-95b53143d2a7?w=800"],
    featured: true,
    categoryTags: ["Hill Station"]
  },
  {
    id: 32,
    title: "River Side Log Cabin",
    type: "farmhouse",
    city: "Manali",
    location: "Beas River, Manali",
    state: "Himachal Pradesh",
    price: 5200,
    rating: 4.9,
    reviews: 14,
    badge: "Superhost",
    images: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"],
    featured: false,
    categoryTags: ["Hill Station"]
  }
];
